spring:
  application:
    name: BASE-MAIN
    type:
  datasource:
    url: jdbc:mysql://localhost:3306/liudao
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
    auto-commit: false

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    jdbc-type-for-null: ''
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl